#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    inventar-api-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^inventar-api\.ddev\.site$`)
      
      service: "inventar-api-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "inventar-api-redirectHttps"
    inventar-api-web-80-http:
      entrypoints:
        - http-33000
      rule: HostRegexp(`^inventar-api\.ddev\.site$`)
      
      service: "inventar-api-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "inventar-api-redirectHttps"
    inventar-api-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^inventar-api\.ddev\.site$`)
      
      service: "inventar-api-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "inventar-api-redirectHttps"
    
    
    inventar-api-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^inventar-api\.ddev\.site$`)
      
      service: "inventar-api-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    inventar-api-web-80-https:
      entrypoints:
        - http-33001
      rule: HostRegexp(`^inventar-api\.ddev\.site$`)
      
      service: "inventar-api-web-80"
      ruleSyntax: v3
      
      tls: true
      
    inventar-api-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^inventar-api\.ddev\.site$`)
      
      service: "inventar-api-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    inventar-api-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    inventar-api-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-inventar-api-xhgui:80
        
    
    inventar-api-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-inventar-api-web:80
        
    inventar-api-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-inventar-api-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/inventar-api.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/inventar-api.key